//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmenu
    {
        public long ID { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public long MenuOrder { get; set; }
        public string IsParent { get; set; }
        public long ParentID { get; set; }
        public string HasChild { get; set; }
    }
}
