//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpropertyimage
    {
        public long ID { get; set; }
        public long PropertyId { get; set; }
        public string ImageUrl { get; set; }
        public string IsApproved { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
