//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpropertymain
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public long ReqType { get; set; }
        public long PTypeId { get; set; }
        public long PCategoryId { get; set; }
        public long PTransactionType { get; set; }
        public long POwnershipType { get; set; }
        public string ConstructionAge { get; set; }
        public long PFurnish { get; set; }
        public string Range { get; set; }
        public string TaxNo { get; set; }
        public System.DateTime Reg_Date { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public Nullable<long> BHK { get; set; }
        public Nullable<long> TotalFloor { get; set; }
        public string Facing { get; set; }
        public Nullable<long> BathRoom { get; set; }
        public string CoveredArea { get; set; }
        public Nullable<decimal> RateSq { get; set; }
        public string Features { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string BStatus { get; set; }
        public string Status { get; set; }
    }
}
