//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpropertyammenity
    {
        public long ID { get; set; }
        public long PropertyId { get; set; }
        public string PowerBackup { get; set; }
        public string LiftService { get; set; }
        public string PlayGround { get; set; }
        public string GYM { get; set; }
        public string PlayingCourt { get; set; }
        public string PartyRoom { get; set; }
        public string StorageSpace { get; set; }
        public string Bedding { get; set; }
    }
}
